// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trapperkeeper_mvc.Models;

namespace trapperkeeper_mvc.Migrations.Finances
{
    [DbContext(typeof(FinancesContext))]
    [Migration("20190523032519_TransactionValidation_v2")]
    partial class TransactionValidation_v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("trapperkeeper_mvc.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Discover"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Arrival Plus"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Uber"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Chase"
                        });
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Fixed"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Flexible"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Variable"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Debt"
                        });
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.Subcategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("Subcategory");
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.TransactionEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountID");

                    b.Property<decimal>("Amount");

                    b.Property<int?>("CategoryID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int?>("SubcategoryID");

                    b.Property<int?>("TransactionLedgerID");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SubcategoryID");

                    b.HasIndex("TransactionLedgerID");

                    b.ToTable("TransactionEntry");
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.TransactionLedger", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("Total");

                    b.HasKey("ID");

                    b.ToTable("TransactionLedger");
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.TransactionEntry", b =>
                {
                    b.HasOne("trapperkeeper_mvc.Models.Account", "Account")
                        .WithMany("TransactionEntries")
                        .HasForeignKey("AccountID");

                    b.HasOne("trapperkeeper_mvc.Models.Category", "Category")
                        .WithMany("TransactionEntries")
                        .HasForeignKey("CategoryID");

                    b.HasOne("trapperkeeper_mvc.Models.Subcategory", "Subcategory")
                        .WithMany("TransactionEntries")
                        .HasForeignKey("SubcategoryID");

                    b.HasOne("trapperkeeper_mvc.Models.TransactionLedger", "TransactionLedger")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionLedgerID");
                });
#pragma warning restore 612, 618
        }
    }
}
