// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trapperkeeper_mvc.Models;

namespace trapperkeeper_mvc.Migrations.Finances
{
    [DbContext(typeof(FinancesContext))]
    [Migration("20190529021649_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("trapperkeeper_mvc.Models.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("AccountID");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            AccountID = 1,
                            Description = "Discover"
                        },
                        new
                        {
                            AccountID = 2,
                            Description = "Arrival Plus"
                        },
                        new
                        {
                            AccountID = 3,
                            Description = "Uber"
                        },
                        new
                        {
                            AccountID = 4,
                            Description = "Chase"
                        },
                        new
                        {
                            AccountID = 5,
                            Description = "Ally Checking"
                        });
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "Fixed"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "Flexible"
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "Variable"
                        },
                        new
                        {
                            CategoryID = 4,
                            Description = "Debt"
                        });
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.Subcategory", b =>
                {
                    b.Property<int>("SubcategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("SubcategoryID");

                    b.ToTable("Subcategory");

                    b.HasData(
                        new
                        {
                            SubcategoryID = 1,
                            Description = "Entertainment"
                        },
                        new
                        {
                            SubcategoryID = 2,
                            Description = "Restaurants"
                        },
                        new
                        {
                            SubcategoryID = 3,
                            Description = "Groceries"
                        },
                        new
                        {
                            SubcategoryID = 4,
                            Description = "Gasoline"
                        },
                        new
                        {
                            SubcategoryID = 5,
                            Description = "Booze"
                        },
                        new
                        {
                            SubcategoryID = 6,
                            Description = "Professional"
                        },
                        new
                        {
                            SubcategoryID = 7,
                            Description = "Health"
                        },
                        new
                        {
                            SubcategoryID = 8,
                            Description = "Clothing"
                        },
                        new
                        {
                            SubcategoryID = 9,
                            Description = "Gifts"
                        },
                        new
                        {
                            SubcategoryID = 10,
                            Description = "Car"
                        },
                        new
                        {
                            SubcategoryID = 11,
                            Description = "Home"
                        },
                        new
                        {
                            SubcategoryID = 12,
                            Description = "Fees"
                        },
                        new
                        {
                            SubcategoryID = 13,
                            Description = "Dog"
                        },
                        new
                        {
                            SubcategoryID = 14,
                            Description = "Subscriptions"
                        });
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.TransactionEntry", b =>
                {
                    b.Property<int>("TransactionEntryID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountID");

                    b.Property<decimal>("Amount");

                    b.Property<int?>("CategoryID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int?>("SubcategoryID");

                    b.Property<int?>("TransactionLedgerID");

                    b.HasKey("TransactionEntryID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SubcategoryID");

                    b.HasIndex("TransactionLedgerID");

                    b.ToTable("TransactionEntry");
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.TransactionLedger", b =>
                {
                    b.Property<int>("TransactionLedgerID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("Total");

                    b.HasKey("TransactionLedgerID");

                    b.ToTable("TransactionLedger");
                });

            modelBuilder.Entity("trapperkeeper_mvc.Models.TransactionEntry", b =>
                {
                    b.HasOne("trapperkeeper_mvc.Models.Account", "Account")
                        .WithMany("TransactionEntries")
                        .HasForeignKey("AccountID");

                    b.HasOne("trapperkeeper_mvc.Models.Category", "Category")
                        .WithMany("TransactionEntries")
                        .HasForeignKey("CategoryID");

                    b.HasOne("trapperkeeper_mvc.Models.Subcategory", "Subcategory")
                        .WithMany("TransactionEntries")
                        .HasForeignKey("SubcategoryID");

                    b.HasOne("trapperkeeper_mvc.Models.TransactionLedger", "TransactionLedger")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionLedgerID");
                });
#pragma warning restore 612, 618
        }
    }
}
